# Generated by Django 3.1 on 2020-09-06 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skill_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('another', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('skill_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.skills')),
            ],
        ),
    ]
