# Generated by Django 3.1 on 2020-09-06 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skill_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food.skills'),
        ),
    ]
